// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8157MqZ7J2EWeOe-ONRn9HJ9m58e3mEM',
    appId: '1:854883071659:web:59861f81071e73a68d69ee',
    messagingSenderId: '854883071659',
    projectId: 'medichain-app',
    authDomain: 'medichain-app.firebaseapp.com',
    storageBucket: 'medichain-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0YBQnv-w3xQMnQ7EC4vKLeEpXlSu485k',
    appId: '1:854883071659:android:c5ffcc58d5ca2d3d8d69ee',
    messagingSenderId: '854883071659',
    projectId: 'medichain-app',
    storageBucket: 'medichain-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNU3HSizgbFA4VAfdz33opxycJ7RD-h8U',
    appId: '1:854883071659:ios:6fcbdfd7753223da8d69ee',
    messagingSenderId: '854883071659',
    projectId: 'medichain-app',
    storageBucket: 'medichain-app.firebasestorage.app',
    iosBundleId: 'com.example.medichainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNU3HSizgbFA4VAfdz33opxycJ7RD-h8U',
    appId: '1:854883071659:ios:6fcbdfd7753223da8d69ee',
    messagingSenderId: '854883071659',
    projectId: 'medichain-app',
    storageBucket: 'medichain-app.firebasestorage.app',
    iosBundleId: 'com.example.medichainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8157MqZ7J2EWeOe-ONRn9HJ9m58e3mEM',
    appId: '1:854883071659:web:d0445d1c0d7c112f8d69ee',
    messagingSenderId: '854883071659',
    projectId: 'medichain-app',
    authDomain: 'medichain-app.firebaseapp.com',
    storageBucket: 'medichain-app.firebasestorage.app',
  );
}
